import type { AstroIntegration } from 'astro';
import { list } from '@vercel/blob';
import probe from 'probe-image-size';
import { writeFile, mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';

interface BlobEntry {
  url: string;
  width: number | null;
  height: number | null;
}

const GENERATED_PATH = 'src/generated/blob-manifest.ts';

function inferContentType(pathname: string): string {
  const ext = pathname.split('.').pop()?.toLowerCase() ?? '';
  switch (ext) {
    case 'svg':
      return 'image/svg+xml';
    case 'jpg':
    case 'jpeg':
      return 'image/jpeg';
    case 'png':
      return 'image/png';
    case 'webp':
      return 'image/webp';
    case 'avif':
      return 'image/avif';
    case 'gif':
      return 'image/gif';
    default:
      return 'application/octet-stream';
  }
}

async function buildManifest(): Promise<Record<string, BlobEntry>> {
  const token = process.env.BLOB_READ_WRITE_TOKEN;
  if (!token) {
    throw new Error(
      'BLOB_READ_WRITE_TOKEN is not set. ' +
        'Pull it with `vercel env pull .env.local`, or add it to .env. ' +
        'Without it, the Vercel Blob manifest cannot be built.',
    );
  }

  const { blobs } = await list({ token });
  const manifest: Record<string, BlobEntry> = {};

  for (const blob of blobs) {
    const contentType = inferContentType(blob.pathname);
    const dims = await probeDims(blob.url, blob.pathname, contentType);
    manifest[blob.pathname] = {
      url: blob.url,
      width: dims?.width ?? null,
      height: dims?.height ?? null,
    };
  }

  return manifest;
}

async function probeDims(
  url: string,
  key: string,
  contentType: string,
): Promise<{ width: number; height: number } | null> {
  try {
    const result = await probe(url);
    return { width: result.width, height: result.height };
  } catch (err) {
    if (contentType === 'image/svg+xml') {
      console.warn(
        `[blob-manifest] SVG "${key}" has no intrinsic dimensions; ` +
          `it will render without width/height and rely on CSS sizing.`,
      );
      return null;
    }
    throw new Error(
      `[blob-manifest] Failed to probe dimensions for "${key}": ${(err as Error).message}`,
    );
  }
}

async function writeManifest(manifest: Record<string, BlobEntry>): Promise<void> {
  const sorted = Object.keys(manifest)
    .sort()
    .reduce<Record<string, BlobEntry>>((acc, k) => {
      acc[k] = manifest[k]!;
      return acc;
    }, {});

  const body = `// AUTO-GENERATED by src/integrations/blob-manifest.ts — do not edit.
// Regenerated at \`astro:config:setup\` on every dev/build/check run.
export const BLOB_MANIFEST = ${JSON.stringify(sorted, null, 2)} as const;
export type BlobManifestKey = keyof typeof BLOB_MANIFEST;
`;

  await mkdir('src/generated', { recursive: true });
  await writeFile(resolve(GENERATED_PATH), body, 'utf8');
}

export function blobManifest(): AstroIntegration {
  return {
    name: 'hotrod-blob-manifest',
    hooks: {
      'astro:config:setup': async ({ logger }) => {
        logger.info('Building Blob manifest...');
        const manifest = await buildManifest();
        await writeManifest(manifest);
        logger.info(
          `Blob manifest written: ${Object.keys(manifest).length} entries.`,
        );
      },
    },
  };
}
