import type { AstroIntegration } from 'astro';
import Mux from '@mux/mux-node';
import { writeFile, mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';

interface MuxEntry {
  assetId: string;
  aspectRatio: string | null;
  duration: number | null;
  status: string;
  title: string | null;
}

const GENERATED_PATH = 'src/generated/mux-manifest.ts';

async function buildManifest(): Promise<Record<string, MuxEntry>> {
  const tokenId = process.env.MUX_TOKEN_ID;
  const tokenSecret = process.env.MUX_TOKEN_SECRET;
  if (!tokenId || !tokenSecret) {
    throw new Error(
      'MUX_TOKEN_ID and MUX_TOKEN_SECRET must both be set. ' +
        'Pull them with `vercel env pull .env.local --environment=production --yes` from the linked repo. ' +
        'Without them, the Mux manifest cannot be built.',
    );
  }

  const mux = new Mux({ tokenId, tokenSecret });
  const { data: assets } = await mux.video.assets.list({ limit: 100 });

  if (assets.length === 100) {
    console.warn(
      '[mux-manifest] Hit the 100-asset page limit. ' +
        'Pagination is not implemented in v1 — older assets may be missing from the manifest.',
    );
  }

  const manifest: Record<string, MuxEntry> = {};
  for (const asset of assets) {
    for (const pb of asset.playback_ids ?? []) {
      if (pb.policy !== 'public') continue;
      manifest[pb.id] = {
        assetId: asset.id,
        aspectRatio: asset.aspect_ratio ?? null,
        duration: asset.duration ?? null,
        status: asset.status,
        title: asset.meta?.title ?? null,
      };
    }
  }
  return manifest;
}

async function writeManifest(manifest: Record<string, MuxEntry>): Promise<void> {
  const sorted = Object.keys(manifest)
    .sort()
    .reduce<Record<string, MuxEntry>>((acc, k) => {
      acc[k] = manifest[k]!;
      return acc;
    }, {});

  const body = `// AUTO-GENERATED by src/integrations/mux-manifest.ts — do not edit.
// Regenerated at \`astro:config:setup\` on every dev/build/check run.
export const MUX_MANIFEST = ${JSON.stringify(sorted, null, 2)} as const;
export type MuxManifestKey = keyof typeof MUX_MANIFEST;
`;

  await mkdir('src/generated', { recursive: true });
  await writeFile(resolve(GENERATED_PATH), body, 'utf8');
}

export function muxManifest(): AstroIntegration {
  return {
    name: 'hotrod-mux-manifest',
    hooks: {
      'astro:config:setup': async ({ logger }) => {
        logger.info('Building Mux manifest...');
        const manifest = await buildManifest();
        await writeManifest(manifest);
        logger.info(
          `Mux manifest written: ${Object.keys(manifest).length} public playback IDs.`,
        );
      },
    },
  };
}
